packages/composables/src/getters/facetGetters.ts, packages/composables/src/getters/wishlistGetters.ts, packages/theme/components/AppHeader.vue
=> fix: hackathon findings

.github/workflows/test.yml
Adds different operating systems to the package test. This ensures that it's possible to build the app on all operating systems.
=> feat: add OS matrix to packages test

packages/theme/components/CookieBar.vue
=> refactor: cookiebar responsiveness

packages/theme/pages/Category.vue, packages/theme/pages/Checkout/Billing.vue, packages/theme/pages/Checkout/Shipping.vue, packages/theme/pages/MyAccount/BillingDetails.vue, packages/theme/pages/MyAccount/ShippingDetails.vue
Use Loading-Animation for situations where the UI loads elements
=> fix: use loading-animation for situations where the ui loads elements

packages/theme/components/AddressPicker.vue
primary address automatic selection if only 1 present
=> fix: primary address automatic selection if only 1 present

packages/theme/components/Checkout/PsfPersonalDetails.vue
=> feat: changed size of login now link

.github/workflows/test.yml, packages/theme/nuxt.config.js, packages/theme/package.json, packages/theme/tests/e2e/cypress.config.js, packages/theme/tests/e2e/support/index.js, yarn.lock
* Creates code coverage report after running e2e tests
* Extends test workflow to upload report after CI
=> feat: add code coverage report

packages/theme/components/AppHeader.vue, packages/theme/pages/MyAccount.vue
=> fix: my account mobile navigation

packages/theme/tests/e2e/fixtures/order.json
=> chore: added order fixture

packages/api-client/src/index.server.ts
=> fix: missing plentyId cookie header

.github/workflows/test.yml, packages/api-client/src/api/getUser/index.ts, packages/api-client/src/index.server.ts, packages/api-client/src/types/apiMethods.ts, packages/api-client/src/types/events.ts, packages/composables/src/useCookieBar/index.ts, packages/composables/src/useUser/index.ts, packages/theme/components/CartSidebar.vue, packages/theme/components/CookieBar.vue, packages/theme/layouts/default.vue, packages/theme/nuxt.config.js, packages/theme/plugins/api-cookies.ts, packages/theme/tests/e2e/cypress.config.js, packages/theme/tests/e2e/e2e/cart.cy.ts, packages/theme/tests/e2e/e2e/cookiebar.cy.ts, packages/theme/tests/e2e/e2e/place-order.cy.ts, packages/theme/tests/e2e/e2e/register-account.cy.ts, packages/theme/tests/e2e/pages/components/cart-sidebar.ts, packages/theme/tests/e2e/pages/utils/cookie.ts, packages/theme/tests/e2e/pages/utils/element.ts
=> fix: middleware set cookie

packages/api-client/src/api/getOrder/index.ts, packages/api-client/src/types/apiMethods.ts, packages/api-client/src/types/order.ts, packages/composables/src/getters/orderGetters.ts, packages/composables/src/useOrder/index.ts, packages/theme/components/LoginForm.vue, packages/theme/components/SoftLogin.vue, packages/theme/pages/Checkout/Payment.vue, packages/theme/pages/Checkout/ThankYou.vue
=> feat: soft login implementation

packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/Checkout/ThankYou.vue
=> feat: show order basic data

packages/composables/src/getters/orderGetters.ts, packages/theme/components/OrderTotals.vue, packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/Checkout/ThankYou.vue
=> feat: order totals rework

packages/api-client/src/api/getCart/index.ts, packages/theme/middleware.config.js
=> fix: cart items delete

packages/theme/assets/scss/theme.scss
=> fix: changed primary color in theme to fix accessibility error

packages/theme/nuxt.config.js
=> fix: server ip to localhost

packages/api-client/src/api/getUser/index.ts, packages/composables/src/useUser/index.ts
moved login/logout/guest routes from io to storefront
=> feat: replace io routes to storefront

packages/api-client/src/api/getOrder/index.ts, packages/api-client/src/types/order.ts
=> fix: update order/additional_information route

packages/api-client/src/api/getOrder/index.ts, packages/api-client/src/types/apiMethods.ts, packages/api-client/src/types/order.ts, packages/composables/src/useMakeOrder/index.ts, packages/theme/middleware.config.js
=> feat: use storefront order route

packages/api-client/src/api/getAddress/index.ts, packages/api-client/src/types/address.ts, packages/theme/assets/scss/theme.scss
=> fix: new rest calls for addresses

packages/theme/components/LoginForm.vue, packages/theme/components/LoginModal.vue, packages/theme/components/MyAccount/NewsletterSubscribeForm.vue, packages/theme/tailwind.config.js
fix for button height while loading
=> fix: button height fix while loading

packages/theme/components/Checkout/VsfShippingProvider.vue, packages/theme/lang/de.js, packages/theme/lang/en.js
shipping provider replace 0 amount text with 'free'
=> feat: shipping provider free amount description

.eslintrc.json, packages/api-client/src/api/getSearch/index.ts, packages/composables/src/useCart/index.ts, packages/composables/src/useCookieBar/index.ts, packages/composables/src/useForgotPassword/index.ts, packages/composables/src/useReview/index.ts, packages/composables/src/useStore/index.ts, packages/composables/src/useUser/index.ts, packages/composables/src/useUserShipping/index.ts, packages/composables/src/useWishlist/index.ts, packages/theme/components/MyAccount/PsfMyProfile.vue, packages/theme/composables/useUiHelpers/index.ts, packages/theme/pages/Home.vue
Updates the ESLint config to throw an error if any console methods remain in the code.
This PR also resolves all existing console logs.
The main reason is to prevent console logs used for debugging from reaching production.
=> feat: throw error for console msgs

.github/workflows/upload.yml
=> feat: added tar instead of zipper

packages/api-client/src/types/order.ts, packages/composables/src/getters/orderGetters.ts, packages/theme/components/DocumentsList.vue, packages/theme/nuxt.config.js, packages/theme/pages/Checkout/ThankYou.vue, packages/theme/pages/MyAccount/OrderHistory.vue
Buttons for viewing documents of order if order has documents
=> feat: added test buttons

packages/theme/components/AppHeader.vue, packages/theme/components/HeaderNavigation.vue, packages/theme/pages/Checkout.vue, packages/theme/pages/Checkout/Billing.vue, packages/theme/pages/Checkout/Login.vue, packages/theme/pages/Checkout/Payment.vue, packages/theme/pages/Checkout/Shipping.vue, packages/theme/pages/MyAccount.vue
This helps us to migrate faster to Vue 3 script setup
Closes: 63004
Replace root.localePath() with app.localePath()
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.
=> feat: refactored .localePath in whole app

packages/theme/components/TopBar.vue, packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/Product.vue
Remove code and ui elements that we haven't implemented yet or don't need.
Closes: 
[AB#63863](https://dev.azure.com/plentymarkets/0af57df9-8662-4901-bb97-8e88b07ff0c9/_workitems/edit/63863)
=> refactor: cleanup single item & header

packages/api-client/src/api/getOrder/index.ts, packages/api-client/src/types/apiMethods.ts, packages/composables/src/useMakeReturn/index.ts
=> feat: make order return route

packages/theme/components/LoginModal.vue, packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/Checkout/Login.vue, packages/theme/pages/Product.vue
=> fix: email already exists, add to basket placement

packages/theme/pages/Checkout/Shipping.vue, packages/theme/tests/e2e/e2e/checkout.cy.ts
=> refactor: same as billing default true

packages/theme/components/MyAccount/PsfMyProfile.vue, packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/MyAccount/ProfileDetails.vue
- Adding success/error messages
- Adding loading spinner
- Add translations
Closes:
=> refactor: change password page

packages/theme/components/AppFooter.vue, packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/Checkoutreadonly.vue, packages/theme/pages/MyAccount.vue
- footer link hover
- checkoutreadonly clearer texts / labels
- myaccount & checkoutreadonly noindex
Closes:
=> refactor: review feedback changes

packages/composables/src/getters/productGetters.ts, packages/theme/components/BasePrice.vue
https://dev.azure.com/plentymarkets/plentymarkets/_sprints/taskboard/BD%20-%20Team%20-%20LM/plentymarkets/Areas/Sprint%2034?workitem=65790
=> fix: formater and spacing

packages/api-client/src/api/getProduct/index.ts, packages/api-client/src/api/getSearch/index.ts, packages/theme/middleware.config.js
=> feat: item search route

packages/api-client/src/api/getNewsletter/index.ts, packages/api-client/src/types/apiMethods.ts, packages/api-client/src/types/newsletter.ts, packages/composables/src/useNewsletter/index.ts, packages/theme/components/MyAccount/NewsletterUnsubscribeForm.vue
=> feat: newsletter storefront routes

packages/theme/lang/de.js, packages/theme/lang/en.js, packages/theme/pages/Checkout/Payment.vue, packages/theme/tests/e2e/pages/checkout.ts
=> fix: change naming because of legal requirement
